=== nixpoe/videospotovi/schema.json
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "http://example.com/example.json",
    "type": "array",
    "title": "YouTube Spotovi",
    "description": "Skup spotova objavljenih na YouTube platformu",
    "items": {
        "type": "object",
        "title": "YouTube Spotovi",
        "required": [
            "Naslov",
            "Redatelj",
            "Label",
            "Datum",
            "Trajanje_sekunde",
            "Zanr",
            "Pregledi",
            "Komentari",
            "Lajkovi",
            "Izvodaci"
        ],
        "properties": {
            "Naslov": {
                "type": "string",
                "title": "Naslov"
            },
            "Redatelj": {
                "type": "string",
                "title": "Redatelj"
            },
            "Label": {
                "type": "string",
                "title": "Izdavačka kuća"
            },
            "Datum": {
                "type": "string",
                "title": "Datum"
            },
            "Trajanje_sekunde": {
                "type": "integer",
                "title": "Trajanje u sekundama"
            },
            "Zanr": {
                "type": "string",
                "title": "Žanr"
            },
            "Pregledi": {
                "type": "integer",
                "title": "Broj pregleda"
            },
            "Komentari": {
                "type": "integer",
                "title": "Broj komentara"
            },
            "Lajkovi": {
                "type": "integer",
                "title": "Broj lajkova"
            },
            "Izvodaci": {
                "type": "array",
                "title": "Izvođači",
                "items": {
                    "type": "string",
                    "title": "A Schema"
                }
            }
        }
    }
}

=== nixpoe/videospotovi/music_videos.json
[
  {
    "Naslov": "Drake - First Person Shooter ft. J. Cole",
    "Redatelj": "Gibson Hazard",
    "Label": "OVO",
    "Datum": "2023-11-15",
    "Trajanje_sekunde": 300,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 67461946,
    "Komentari": 61134,
    "Lajkovi": 1200000,
    "Izvodaci": [
      "Drake",
      "J. Cole"
    ]
  },
  {
    "Naslov": "Travis Scott - FE!N ft. Playboi Carti ",
    "Redatelj": "Gabriel Moses",
    "Label": "Cactus Jack Records",
    "Datum": "2024-03-30",
    "Trajanje_sekunde": 209,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 100240856,
    "Komentari": 51076,
    "Lajkovi": 1700000,
    "Izvodaci": [
      "Playboi Carti",
      "Travis Scott"
    ]
  },
  {
    "Naslov": "Travis Scott - Drugs You Should Try It ",
    "Redatelj": "Jordan Hemingway",
    "Label": "Cactus Jack Records",
    "Datum": "2024-08-27",
    "Trajanje_sekunde": 208,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 6595208,
    "Komentari": 12610,
    "Lajkovi": 280000,
    "Izvodaci": [
      "Travis Scott"
    ]
  },
  {
    "Naslov": "Travis Scott - MO CITY FLEXOLOGIST",
    "Redatelj": "Kahlil Joseph",
    "Label": "Cactus Jack Records",
    "Datum": "2024-09-24",
    "Trajanje_sekunde": 216,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 6538357,
    "Komentari": 7559,
    "Lajkovi": 275000,
    "Izvodaci": [
      "Travis Scott"
    ]
  },
  {
    "Naslov": "THOUGHT I WAS DEAD",
    "Redatelj": "Tyler Okonma",
    "Label": "Columbia Records",
    "Datum": "2024-10-26",
    "Trajanje_sekunde": 108,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 3784264,
    "Komentari": 24070,
    "Lajkovi": 466000,
    "Izvodaci": [
      "Tyler, The Creator"
    ]
  },
  {
    "Naslov": "NOID",
    "Redatelj": "Tyler Okonma",
    "Label": "Columbia Records",
    "Datum": "2024-10-21",
    "Trajanje_sekunde": 162,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 8689820,
    "Komentari": 31782,
    "Lajkovi": 699000,
    "Izvodaci": [
      "Tyler, The Creator"
    ]
  },
  {
    "Naslov": "Childish Gambino - This Is America (Official Video)",
    "Redatelj": "Hiro Murai",
    "Label": "RCA Records",
    "Datum": "2018-05-06",
    "Trajanje_sekunde": 246,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 934548549,
    "Komentari": 791503,
    "Lajkovi": 12000000,
    "Izvodaci": [
      "Childish Gambino"
    ]
  },
  {
    "Naslov": "KSI - Thick Of It (feat. Trippie Redd) [Official Music Video] ",
    "Redatelj": "KC Locke\\n",
    "Label": "Atlantic Records UK",
    "Datum": "2024-10-03",
    "Trajanje_sekunde": 176,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 44248440,
    "Komentari": 522112,
    "Lajkovi": 922000,
    "Izvodaci": [
      "KSI",
      "Trippie Redd"
    ]
  },
  {
    "Naslov": "EARFQUAKE",
    "Redatelj": "Tyler Okonma",
    "Label": "Columbia Records",
    "Datum": "2019-05-17",
    "Trajanje_sekunde": 266,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 155996909,
    "Komentari": 98431,
    "Lajkovi": 3000000,
    "Izvodaci": [
      "Tyler, The Creator"
    ]
  },
  {
    "Naslov": "Kendrick Lamar - Not Like Us",
    "Redatelj": "Kendrick Lamar, Dave Free",
    "Label": "Interscope Records",
    "Datum": "2024-05-07",
    "Trajanje_sekunde": 354,
    "Zanr": "Hip-hop/Rap",
    "Pregledi": 162807195,
    "Komentari": 289832,
    "Lajkovi": 4900000,
    "Izvodaci": [
      "Kendrick Lamar"
    ]
  }
]
